### ISSUE TITLE
Not possible to import subscriptions json file

### ISSUE THREAD

**Issue by somos61** [RSoulwin/NewPipeToss#1]
### Checklist

- [x] I am using the latest version - Newpipe_legacy_Toss-v0.21.3
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Subscriptions -> Import from -> Previous export

### Actual behaviour

App crashes

### Expected behavior

That is great this fork still allows to use NewPipe on Android <5. But for reasons, it is not possible to import settings from a newer versions, which is actual. So that would be nice at least to import subscriptions json list, if its possible. Thanks

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.1.2
* __OS:__ Linux Android 4.2.2 - 17
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipelegacy.local.subscription.services.SubscriptionsImportService@42623cb8 with Intent { cmp=org.schabi.newpipelegacy.Toss/org.schabi.newpipelegacy.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2866)
	at android.app.ActivityThread.access$1900(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5410)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.schabi.newpipelegacy.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:121)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2849)
	... 10 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 
 - Device model:

**Comment by ShareASmile** [comment]
![IMG-20230707-WA0000](https://github.com/RSoulwin/NewPipeToss/assets/60492161/b6946d6d-f3d4-4eb3-b1df-80c05ae1998a)
Try Toggling SAF ON/OFF & follow various workarounds:

First Give Storage permission manually to the app or download a video [while  enabling SAF in app's download settings] to a folder say Music Folder to obtain permission to that folder and then place imported subscriptions .json file in that folder. It should import successfully. 

Secondly Try to place the file at different locations (Download, Documents, Movies, ...)

These are only workarounds as upstream NewPipe repo hasn't solved this issue yet with some issues similar to above stacktrace are still open.

**Comment by ShareASmile** [comment]
Btw i have lowered target api to 29 in the latest extractor commit try [revo releases](https://github.com/ShareASmile/NewPipe-Legacy-Revo/releases)
